POST http://localhost:8080/media/multipart
Content-Type: multipart/form-data; boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="image"; filename="media.jpg"
Content-Type: image/jpeg

< media.jpg

--WebBoundary

> {%
client.global.set('mediaName', response.body.file);
%}

### REST

GET http://localhost:8080/application/getAll

###

GET http://localhost:8080/application/getById?id=4

###

GET http://localhost:8080/application/getById/4

###

GET http://localhost:8080/application/getById?id=999

###

POST http://localhost:8080/application/save
Content-Type: application/json

{
  "id": 0,
  "personId": "1",
  "eventId": "1",
  "disciplinesId": "2",
  "organizationId": "1",
  "weaponId": "2",
  "weaponManufacturer": "Калашников",
  "permitSerial": "AK",
  "permitNum": "8888888",
  "permitDate": "02.03.2020",
  "permitManufacturer": "Психодиспансер",
  "image": "{{mediaName}}"
 }

###

POST http://localhost:8080/application/removeById?id=4

###

POST http://localhost:8080/application/removeById/4

###

POST http://localhost:8080/application/restoreById?id=4

###

POST http://localhost:8080/application/restoreById/4

###


