POST http://localhost:8080/media/multipart
Content-Type: multipart/form-data; boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="image"; filename="media.jpg"
Content-Type: image/jpeg

< media.jpg

--WebBoundary

> {%
client.global.set('mediaName', response.body.file);
%}

### REST

GET http://localhost:8080/event/getAll

###

GET http://localhost:8080/event/getById?id=1

###

GET http://localhost:8080/event/getById/1

###

GET http://localhost:8080/event/getById?id=999

###

POST http://localhost:8080/event/save
Content-Type: application/json

{
  "id": 0,
  "name": "Happy New Year",
  "image": "0a85f333-c05b-47ec-96ec-238904c0a331.jpg"
}

###

POST http://localhost:8080/event/save
Content-Type: application/json

{
  "id": 0,
  "name": "Happy New Year",
  "image": "{{mediaName}}"
}

###

POST http://localhost:8080/event/removeById?id=7

###

POST http://localhost:8080/event/removeById/1

###

POST http://localhost:8080/event/restoreById?id=7

###

POST http://localhost:8080/event/restoreById/1

###


