POST http://localhost:8080/media/multipart
Content-Type: multipart/form-data; boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="image"; filename="media.jpg"
Content-Type: image/jpeg

< media.jpg

--WebBoundary

> {%
client.global.set('mediaName', response.body.file);
%}
###


### REST

GET http://localhost:8080/person/getAll

###

GET http://localhost:8080/person/getById?id=2

###

GET http://localhost:8080/person/getById/2

###

GET http://localhost:8080/person/getById?id=999

###

POST http://localhost:8080/person/save
Content-Type: application/json

{
  "id": 0,
  "name": "Ivan",
  "surname": "Ivanov",
  "patronymic": "Ivanovich",
  "birthday": "01.01.2001",
  "phone": "89377777777",
  "email": "test999java@gmail.com",
  "citizenshipId": "1",
  "countryId": "1",
  "gender": "M",
  "image": "{{mediaName}}"
}

###

POST http://localhost:8080/person/removeById?id=9

###

POST http://localhost:8080/person/removeById/1

###

POST http://localhost:8080/person/restoreById?id=9

###

POST http://localhost:8080/person/restoreById/1

###

POST http://localhost:8080/person/sandMailByStatus?id=1&status=1





