POST http://localhost:8080/media/multipart
Content-Type: multipart/form-data; boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="file"; filename="media.jpg"
Content-Type: image/jpeg

< media.jpg

> {%
client.global.set('mediaName', response.body.name);
%}
--WebBoundary

###

POST http://localhost:8080/media/multi-multipart
Content-Type: multipart/form-data; boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="files"; filename="media.jpg"
Content-Type: image/jpeg

< media.jpg
--WebBoundary
Content-Disposition: form-data; name="files"; filename="music.mp3"
Content-Type: audio/mpeg

< music.mp3
--WebBoundary--

### REST

GET http://localhost:8080/person/getAll

###

GET http://localhost:8080/person/getById?id=1

###

GET http://localhost:8080/person/getById/1

###

GET http://localhost:8080/person/getById?id=999

###

POST http://localhost:8080/person/save
Content-Type: application/json

{
  "id": 0,
  "name": "Ivan",
  "surname": "Ivanov",
  "patronymic": "Ivanovich",
  "birthday": "01.01.2001",
  "phone": "89377777777",
  "email": "email@mail.ru",
  "citizenshipId": "1",
  "countryId": "1",
  "gender": "M",
  "image": "0a85f333-c05b-47ec-96ec-238904c0a331.jpg"
}

###

POST http://localhost:8080/person/save
Content-Type: application/json

{
  "id": 0,
  "name": "Ivan",
  "surname": "Ivanov",
  "patronymic": "Ivanovich",
  "birthday": "01.01.2001",
  "phone": "89377777777",
  "email": "email@mail.ru",
  "citizenshipId": "1",
  "countryId": "1",
  "gender": "M",
  "image": "{{mediaName}}"
}

###

POST http://localhost:8080/person/removeById?id=1

###

POST http://localhost:8080/person/removeById/1