POST http://localhost:8080/media/multipart
Content-Type: multipart/form-data; boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="image"; filename="media.jpg"
Content-Type: image/jpeg

< media.jpg

--WebBoundary

> {%
client.global.set('mediaName', response.body.file);
%}

### REST

GET http://localhost:8080/weapon/getAll

###

GET http://localhost:8080/weapon/getById?id=2

###

GET http://localhost:8080/weapon/getById/2

###

GET http://localhost:8080/weapon/getById?id=999

###

POST http://localhost:8080/weapon/save
Content-Type: application/json

{
  "id": 0,
  "name": "Макаров",
  "image": "{{mediaName}}"
}

###

POST http://localhost:8080/weapon/removeById?id=5

###

POST http://localhost:8080/weapon/removeById/1

###

POST http://localhost:8080/weapon/restoreById?id=1

###

POST http://localhost:8080/weapon/restoreById/1

###

